---
title: "mlb_sp_clustering"
author: "Tyler Fuelling"
date: "August 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load libraries
library(VIM)
library(dplyr)
library(mice)
library(sjmisc)
library(purrr)
library(factoextra)
library(cluster)
library(sjmisc)
```

```{r}
# read the data file into a dataframe
df <- read.csv("sp_data.csv", header = TRUE, check.names = TRUE)
head(df)
```
``` {r}
# renaming the columns of the the df for easier use
colnames(df)[1] <- "name"
df <- df %>% rename(team = Team, ip = IP, k_percent = K., bb_percent = BB., babip = BABIP, gb_percent = GB., ld_percent = LD., fb_percent = FB.,iffb_percent = IFFB.,
                    ev = EV, soft_percent = Soft., med_percent = Med., hard_percent = Hard., fa_percent = FB..1, sl_percent = SL., ct_percent = CT., cb_percent = CB.,
                    ch_percent = CH., sf_percent = SF., kn_percent = KN., fa_standardized_runs = wFB.C, sl_standardized_runs = wSL.C, ct_standardized_runs = wCT.C,
                    cb_standardized_runs = wCB.C, ch_standardized_runs = wCH.C, sf_standardized_runs = wSF.C, kn_standardized_runs = wKN.C, fa_velo = FBv, sl_velo = SLv,
                    ct_velo = CTv, cb_velo = CBv, ch_velo = CHv, sf_velo = SFv, kn_velo = KNv, o_swing_percent = O.Swing., z_swing_percent = Z.Swing., swing_percent = Swing.,
                    o_contact_percent = O.Contact., z_contact_percent = Z.Contact., contact_percent = Contact., zone_percent = Zone., first_strike_percent = F.Strike.,
                    swinging_strike_percent = SwStr., lob_percent = LOB., pace = Pace, player_id = playerid)
```

``` {r}
# examining the NA values present in the dataframe
aggr(df, col=c('navyblue', 'yellow'), numbers = TRUE, sortVars = TRUE, labels = names(df), cex.axis = .7, gap = 3, ylab = c("Missing Data", "Pattern"))
```
``` {r}
# removing the player id column, as well as the three columns related to knuckleballs from the dataframe - none of the starting pitchers had a knuckleball percentage above 0%
df <- subset(df, select = -c(player_id, kn_percent, kn_velo, kn_standardized_runs))
# creating a new subset of the dataframe without the name and team columns to be used for multivariate imputation (MICE package)
mice_subset <- subset(df, select = -c(name, team))

# Multivariate Imputation via Chained Equations
# creating 15 imputed data sets because the original data set contained about 15% NA's, max iterations of 50, using "predictive mean matching"
imputed_data <- mice(mice_subset, m = 15, maxit = 50, method = 'pmm', seed = 123)

# merging the 15 imputed data sets and appending the imputed data to the mice_subset dataframe
mice_subset <- merge_imputations(mice_subset, imputed_data, mice_subset)
# removing the columns containing NA's from the dataframe, these were replaced with the imputed data 
mice_subset <- mice_subset[colSums(is.na(mice_subset)) == 0]

# verify that there are no more NA's present in the dataframe 
table(is.na(mice_subset))
```

```{r}
# make a copy of the dataframe that contains all of the numerical data, including all of the imputed data
imputed_df <- data.frame(mice_subset)
# add the name and team columns from the original dataframe to this dataframe that contains all of the data
imputed_df$name <- df$name
imputed_df$team <- df$team

# reorganizing the order of the columns of the dataframe
imputed_df <- imputed_df[c(42, 43, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 13, 27, 28, 29, 30, 31, 14, 32, 33, 34, 35, 36,
                           15, 37, 38, 39, 40, 41)]

# standardizing the data so that it can be used for k-means clustering
standardized_imputed_df <- data.frame(imputed_df)
standardized_imputed_df[c(3:43)] <- scale(standardized_imputed_df[c(3:43)])
head(standardized_imputed_df)
```

``` {r}
# determining the optimal number of clusters to use for k-means clustering

set.seed(123) # set the seed so that the clustering achieves the same result each time it is run
possible_k_values <- 1:15 # we will be checking k values of 1 through 15

# Elbow Method

# function that returns the total within-cluster sum of squares for the result of k-means clustering with k clusters
get_total_wss <- function(k) {
  kmeans(standardized_imputed_df[, 3:43], k, nstart = 25)$tot.withinss
}
# calculate the total within-cluster sum of squares for k-means clustering with k values of 1 through 15
total_wss_values <- map_dbl(possible_k_values, get_total_wss)

plot(possible_k_values, total_wss_values, type = "b", frame = FALSE, xlab= "Number of Clusters - K",
     ylab = "Total Within-Cluster Sum of Squares", main = "The Elbow Method")

# Silhouette Analysis

possible_k_values <- 2:15 # skip k value of 1 so we don't get an error when calculating average silhouettes

# function that calculates the average silhouette for the result of k-means clustering with k clusters
get_avg_silhouette <- function(k) {
  clstrs <- kmeans(standardized_imputed_df[, 3:43], k, nstart = 25)
  silhouettes <- silhouette(clstrs$cluster, dist(standardized_imputed_df[, 3:43]))
  mean(silhouettes[, "sil_width"])
}

# calculate the average silhouette for k-means clustering with k values of 1 through 15
avg_silhouette_values <- map_dbl(possible_k_values, get_avg_silhouette)

plot(possible_k_values, avg_silhouette_values, type = "b", frame = FALSE, xlab= "Number of Clusters - K",
     ylab = "Average Silhouette", main = "Silhouette Analysis")

```

``` {r}
# based on the Elbow Method and Silhouette Analysis, we will choose 3 as our value of k for k-means clustering
set.seed(123) # set seed

# k-means clustering with k = 3
clusters <- kmeans(standardized_imputed_df[, 3:43], 3, nstart = 25)

# add each player's cluster to the original dataframe and the imputed dataframe
df$cluster <- as.factor(clusters$cluster)
imputed_df$cluster <- as.factor(clusters$cluster)
df <- df[c(1, 2, 44, 3:43)]
imputed_df <- imputed_df[c(1, 2, 44, 3:43)]
```

``` {r}
# create seperate dataframes for each of the three clusters for both the original data and the imputed data
cluster1 <- subset(df, cluster == "1")
cluster2 <- subset(df, cluster == "2")
cluster3 <- subset(df, cluster == "3")
cluster1_imputed <- subset(imputed_df, cluster == "1")
cluster2_imputed <- subset(imputed_df, cluster == "2")
cluster3_imputed <- subset(imputed_df, cluster == "3")

# calculating each cluster's means for each attribute
cluster1_avgs <- colMeans(cluster1_imputed[sapply(cluster1_imputed, is.numeric)])
cluster2_avgs <- colMeans(cluster2_imputed[sapply(cluster2_imputed, is.numeric)]) 
cluster3_avgs <- colMeans(cluster3_imputed[sapply(cluster3_imputed, is.numeric)])

# create a new dataframe of the per-cluster averages
cluster_avgs <- data.frame(cluster1_avgs, cluster2_avgs, cluster3_avgs)
```
